name = "dawn-cloud-c3c5"
main = "cloudflare-worker-create-order.js"
compatibility_date = "2024-01-01"

[vars]
SUPABASE_URL = "https://effbmnisoxqefwauizib.supabase.co"
RAZORPAY_KEY_ID = "rzp_live_SF5P93aBJVjkFB"
